name: Deploy the static file to GitHub Page
on: [push]

permissions:
  contents: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v7

    - name: deploy docs
      uses: ./
      with:
        username: github-actions[bot]
        password: ${{ secrets.GITHUB_TOKEN }}
        remote_url: https://github.com/appleboy/gh-pages-action.git

    - name: deploy to target directory
      uses: ./
      with:
        username: github-actions[bot]
        password: ${{ secrets.GITHUB_TOKEN }}
        remote_url: https://github.com/appleboy/gh-pages-action.git
        target_directory: 2020

    - name: exclude list
      uses: ./
      with:
        username: github-actions[bot]
        password: ${{ secrets.GITHUB_TOKEN }}
        remote_url: https://github.com/appleboy/gh-pages-action.git
        commit_author: Bo-Yi Wu
        commit_author_email: appleboy.tw@gmail.com
        target_directory: ignore
        exclude: ignore.html
